[package]
name = "harm-asm-regen"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
authors = ["Ivan Boldyrev <lispnik@gmail.com>"]
publish = false

[dependencies]
eyre = "0.6.12"
tempfile = "3.20.0"
