/* Tests based on code generated by Claude Sonnet 4.6 in March 2026.
 */
use super::*;

// ═══════════════════════════════════════════════════════════════════════
// Test helpers
// ═══════════════════════════════════════════════════════════════════════

const MOV_W_OPC_MOVZ: u32 = 0b10;
const MOV_W_OPC_MOVN: u32 = 0b00;

// ── Byte-level readers ────────────────────────────────────────────────

fn u16_at(mem: &[u8], off: usize) -> u16 {
    u16::from_le_bytes(mem[off..off + 2].try_into().unwrap())
}
fn u32_at(mem: &[u8], off: usize) -> u32 {
    u32::from_le_bytes(mem[off..off + 4].try_into().unwrap())
}
fn u64_at(mem: &[u8], off: usize) -> u64 {
    u64::from_le_bytes(mem[off..off + 8].try_into().unwrap())
}

// ── Instruction-field decoders ────────────────────────────────────────

/// Sign-extend the lowest `width` bits of `raw` to i32.
fn sign_ext(raw: u32, width: u32) -> i32 {
    let sh = 32 - width;
    ((raw << sh) as i32) >> sh
}

fn dec_imm14(insn: u32) -> i32 {
    sign_ext((insn >> 5) & 0x3FFF, 14)
}
fn dec_imm19(insn: u32) -> i32 {
    sign_ext((insn >> 5) & 0x007F_FFFF, 19)
}
fn dec_imm26(insn: u32) -> i32 {
    sign_ext(insn & 0x03FF_FFFF, 26)
}
fn dec_imm12(insn: u32) -> u32 {
    (insn >> 10) & 0xFFF
}
fn dec_movw(insn: u32) -> u16 {
    ((insn >> 5) & 0xFFFF) as u16
}

fn dec_imm21_adr(insn: u32) -> i32 {
    let lo = (insn >> 29) & 0x3;
    let hi = (insn >> 5) & 0x0007_FFFF;
    sign_ext((hi << 2) | lo, 21)
}

fn mov_w_opc(insn: u32) -> u32 {
    (insn >> 29) & 0x3
}

// ── Skeleton instruction words ────────────────────────────────────────

// LDR  X0, #0           → 0x5800_0000
const LDR_LIT: u32 = 0x5800_0000;
// ADR  X1, #0           → 0x0000_0001
const ADR: u32 = 0x0000_0001;
// ADRP X0, #0           → 0x9000_0000
const ADRP: u32 = 0x9000_0000;
// ADD  X0, X1, #0       → 0x9100_0020
const ADD: u32 = 0x9100_0020;
// TBZ  X0, #0, #0       → 0x3600_0000
const TBZ: u32 = 0x3600_0000;
// B.EQ #0               → 0x5400_0000
const BEQ: u32 = 0x5400_0000;
// B    #0               → 0x1400_0000
const B: u32 = 0x1400_0000;
// BL   #0               → 0x9400_0000
const BL: u32 = 0x9400_0000;
// MOVZ X0, #0           → 0xD280_0000
const MOVZ: u32 = 0xD280_0000;

/// Return a 4-byte buffer pre-loaded with an instruction word.
fn insn_buf(insn: u32) -> [u8; 4] {
    insn.to_le_bytes()
}

// ═══════════════════════════════════════════════════════════════════════
// get_bytes_mut / get_bytes
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn get_bytes_mut_ok() {
    let mut mem = [1u8, 2, 3, 4, 5, 6, 7, 8];
    let arr: &mut [u8; 4] = get_bytes_mut(&mut mem, 2).unwrap();
    assert_eq!(*arr, [3, 4, 5, 6]);
}

#[test]
fn get_bytes_mut_invalid_offset() {
    let mut mem = [0u8; 4];
    assert_eq!(
        get_bytes_mut::<4>(&mut mem, 5),
        Err(Rel64Error::InvalidOffset { offset: 5 })
    );
}

#[test]
fn get_bytes_mut_not_enough_memory() {
    let mut mem = [0u8; 4];
    // offset 2 is valid, but only 2 bytes remain — not enough for N=4
    assert_eq!(
        get_bytes_mut::<4>(&mut mem, 2),
        Err(Rel64Error::NotEnoughMemory { offset: 2 })
    );
}

// ═══════════════════════════════════════════════════════════════════════
// Buffer-error variants (exercised through a public function)
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn invalid_offset_error() {
    let mut mem = [0u8; 4];
    assert_eq!(
        abs64_reloc(0, &mut mem, 8),
        Err(Rel64Error::InvalidOffset { offset: 8 })
    );
}

#[test]
fn not_enough_memory_error() {
    let mut mem = [0u8; 4];
    assert_eq!(
        abs64_reloc(0, &mut mem, 0),
        Err(Rel64Error::NotEnoughMemory { offset: 0 })
    );
}

// ═══════════════════════════════════════════════════════════════════════
// abs64  (target, mem, offset)
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn abs64_basic() {
    let mut mem = [0u8; 16];
    abs64_reloc(0xDEAD_BEEF_CAFE_1234, &mut mem, 4).unwrap();
    assert_eq!(u64_at(&mem, 4), 0xDEAD_BEEF_CAFE_1234);
    assert_eq!(&mem[..4], &[0u8; 4]); // guard bytes untouched
}

#[test]
fn abs64_zero() {
    let mut mem = [0xFFu8; 8];
    abs64_reloc(0, &mut mem, 0).unwrap();
    assert_eq!(u64_at(&mem, 0), 0);
}

#[test]
fn abs64_max() {
    let mut mem = [0u8; 8];
    abs64_reloc(u64::MAX, &mut mem, 0).unwrap();
    assert_eq!(u64_at(&mem, 0), u64::MAX);
}

// ═══════════════════════════════════════════════════════════════════════
// abs32  (target, mem, offset)
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn abs32_basic() {
    let mut mem = [0u8; 8];
    abs32_reloc(0x7BCD_1234, &mut mem, 2).unwrap();
    assert_eq!(u32_at(&mem, 2), 0x7BCD_1234);
}

#[test]
fn abs32_neg() {
    let mut mem = [0u8; 4];
    abs32_reloc(-1, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0), (-1i32) as u32);
}

#[test]
fn abs32_max() {
    let mut mem = [0u8; 4];
    abs32_reloc(i32::MAX as i64, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0), i32::MAX as u32);
}

#[test]
fn abs32_overflow() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        abs32_reloc(0x1_0000_0000 as i64, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// abs16  (target, mem, offset)
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn abs16_basic() {
    let mut mem = [0u8; 4];
    abs16_reloc(0x7EEF, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0), 0x7EEF);
}

#[test]
fn abs16_neg() {
    let mut mem = [0u8; 4];
    abs16_reloc(-1, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0), (-1i16) as u16);
}

#[test]
fn abs16_max() {
    let mut mem = [0u8; 2];
    abs16_reloc(i16::MAX as _, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0), i16::MAX as u16);
}

#[test]
fn abs16_overflow() {
    let mut mem = [0u8; 2];
    assert!(matches!(
        abs16_reloc(0x1_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// prel64  (base, target, mem, offset)
//
//   place = base + offset
//   written = target − place  (wrapping u64)
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn prel64_forward() {
    // place = 0x1000 + 0 = 0x1000;  diff = 0x2000 − 0x1000 = +0x1000
    let mut mem = [0u8; 8];
    prel64_reloc(0x1000, 0x2000, &mut mem, 0).unwrap();
    assert_eq!(u64_at(&mem, 0), 0x1000);
}

#[test]
fn prel64_backward() {
    // place = 0x2000;  diff = 0x1000 − 0x2000 (wrapping) = −0x1000
    let mut mem = [0u8; 8];
    prel64_reloc(0x2000, 0x1000, &mut mem, 0).unwrap();
    assert_eq!(u64_at(&mem, 0) as i64, -0x1000i64);
}

#[test]
fn prel64_zero_diff() {
    let mut mem = [0xFFu8; 8];
    prel64_reloc(0x4000, 0x4000, &mut mem, 0).unwrap();
    assert_eq!(u64_at(&mem, 0), 0);
}

#[test]
fn prel64_nonzero_offset() {
    // base=0x0FF8, offset=8 → place=0x1000;  diff=0x2000−0x1000=0x1000
    let mut mem = [0u8; 16];
    prel64_reloc(0x0FF8, 0x2000, &mut mem, 8).unwrap();
    assert_eq!(u64_at(&mem, 8), 0x1000);
}

// ═══════════════════════════════════════════════════════════════════════
// prel32  (base, target, mem, offset)
//
//   diff = target − place;  must fit in [i32::MIN, i32::MAX]
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn prel32_forward() {
    let mut mem = [0u8; 4];
    prel32_reloc(0x4000, 0x5000, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0) as i32, 0x1000);
}

#[test]
fn prel32_backward() {
    // place=0x5000;  diff = 0x4000 − 0x5000 = −0x1000
    let mut mem = [0u8; 4];
    prel32_reloc(0x5000, 0x4000, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0) as i32, -0x1000);
}

#[test]
fn prel32_max_positive() {
    // diff = i32::MAX = 0x7FFF_FFFF — just fits
    let mut mem = [0u8; 4];
    prel32_reloc(0x0, 0x7FFF_FFFF, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0) as i32, i32::MAX);
}

#[test]
fn prel32_max_negative() {
    // place=0x8000_0000;  diff = 0 − 0x8000_0000 = i32::MIN — just fits
    let mut mem = [0u8; 4];
    prel32_reloc(0x8000_0000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0) as i32, i32::MIN);
}

#[test]
fn prel32_overflow_positive() {
    // diff = 0x8000_0000 = i32::MAX + 1
    let mut mem = [0u8; 4];
    assert!(matches!(
        prel32_reloc(0x0, 0x8000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

#[test]
fn prel32_overflow_negative() {
    // place=0x8000_0001;  diff = −0x8000_0001 < i32::MIN
    let mut mem = [0u8; 4];
    assert!(matches!(
        prel32_reloc(0x8000_0001, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

#[test]
fn prel32_nonzero_offset() {
    // base=0x0, offset=8 → place=0x8;  diff=0x1008−0x8=0x1000
    let mut mem = [0u8; 12];
    prel32_reloc(0x0, 0x1008, &mut mem, 8).unwrap();
    assert_eq!(u32_at(&mem, 8) as i32, 0x1000);
}

// ═══════════════════════════════════════════════════════════════════════
// prel16  (base, target, mem, offset)
//
//   diff must fit in [i16::MIN, i16::MAX]
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn prel16_forward() {
    // place=0x3FFF;  diff=0x4000−0x3FFF=+1
    let mut mem = [0u8; 2];
    prel16_reloc(0x3FFF, 0x4000, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0) as i16, 1);
}

#[test]
fn prel16_backward() {
    // place=0x4000;  diff=0x3FFF−0x4000=−1
    let mut mem = [0u8; 2];
    prel16_reloc(0x4000, 0x3FFF, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0) as i16, -1);
}

#[test]
fn prel16_max_positive() {
    let mut mem = [0u8; 2];
    prel16_reloc(0x0, 0x7FFF, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0) as i16, i16::MAX);
}

#[test]
fn prel16_max_negative() {
    // place=0x8000;  diff=0−0x8000=i16::MIN — just fits
    let mut mem = [0u8; 2];
    prel16_reloc(0x8000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0) as i16, i16::MIN);
}

#[test]
fn prel16_overflow_positive() {
    let mut mem = [0u8; 2];
    assert!(matches!(
        prel16_reloc(0x0, 0x8000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

#[test]
fn prel16_overflow_negative() {
    // place=0x8001;  diff=−0x8001 < i16::MIN
    let mut mem = [0u8; 2];
    assert!(matches!(
        prel16_reloc(0x8001, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// ld_prel_lo19  (base, target, mem, offset)
//
//   imm19 = (target − place) / 4
//   Signed 19-bit word offset → byte range [−(1<<20), (1<<20)−4]
//   target must be 4-byte aligned relative to place
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn ld_prel_lo19_forward() {
    // place=0;  diff=8;  imm19=2
    let mut mem = insn_buf(LDR_LIT);
    ld_prel_lo19_reloc(0x0, 0x0008, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), 2);
}

#[test]
fn ld_prel_lo19_backward() {
    // place=0x100;  diff=−0x100;  imm19=−64
    let mut mem = insn_buf(LDR_LIT);
    ld_prel_lo19_reloc(0x0100, 0x0000, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), -64);
}

#[test]
fn ld_prel_lo19_max_positive() {
    // imm19 max = (1<<18)−1 word offsets = 0x3_FFFF → byte diff = 0x0F_FFFC
    let mut mem = insn_buf(LDR_LIT);
    ld_prel_lo19_reloc(0x0, 0x0F_FFFC, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), (1 << 18) - 1);
}

#[test]
fn ld_prel_lo19_max_negative() {
    // imm19 min = −(1<<18) word offsets → byte diff = −0x10_0000
    // place=0x10_0000, target=0
    let mut mem = insn_buf(LDR_LIT);
    ld_prel_lo19_reloc(0x10_0000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), -(1 << 18));
}

#[test]
fn ld_prel_lo19_overflow_positive() {
    // byte diff = 0x10_0000 → word imm = 1<<18, one above max
    let mut mem = [0u8; 4];
    assert!(matches!(
        ld_prel_lo19_reloc(0x0, 0x10_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 19,
            align: 2
        }))
    ));
}

#[test]
fn ld_prel_lo19_overflow_negative() {
    // place=0x10_0004, target=0 → byte diff=−0x10_0004 → one below min
    let mut mem = [0u8; 4];
    assert!(matches!(
        ld_prel_lo19_reloc(0x10_0004, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 19,
            align: 2
        }))
    ));
}

#[test]
fn ld_prel_lo19_unaligned() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        ld_prel_lo19_reloc(0x0, 0x0002, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Alignment { align: 2 }))
    ));
}

#[test]
fn ld_prel_lo19_nonzero_offset() {
    // base=0, offset=4 → place=4;  diff=0x10−4=0xC;  imm19=3
    let mut mem = [0u8; 8];
    mem[4..8].copy_from_slice(&LDR_LIT.to_le_bytes());
    ld_prel_lo19_reloc(0x0, 0x10, &mut mem, 4).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 4)), 3);
}

// ═══════════════════════════════════════════════════════════════════════
// adr_prel_lo21  (base, target, mem, offset)
//
//   imm21 = target − place  (byte offset, not scaled)
//   Signed 21-bit → byte range [−(1<<20), (1<<20)−1]
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn adr_prel_lo21_forward() {
    // place=0x1000;  diff=4;  imm21=4
    let mut mem = insn_buf(ADR);
    adr_prel_lo21_reloc(0x1000, 0x1004, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 4);
}

#[test]
fn adr_prel_lo21_backward() {
    // place=0x1000;  diff=0x0FF8−0x1000=−8
    let mut mem = insn_buf(ADR);
    adr_prel_lo21_reloc(0x1000, 0x0FF8, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), -8);
}

#[test]
fn adr_prel_lo21_max_positive() {
    // max diff = (1<<20)−1 = 0xF_FFFF
    let mut mem = insn_buf(ADR);
    adr_prel_lo21_reloc(0x0, 0x0F_FFFF, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), (1 << 20) - 1);
}

#[test]
fn adr_prel_lo21_max_negative() {
    // min diff = −(1<<20) = −0x10_0000;  place=0x10_0000, target=0
    let mut mem = insn_buf(ADR);
    adr_prel_lo21_reloc(0x10_0000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), -(1 << 20));
}

#[test]
fn adr_prel_lo21_overflow_positive() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        adr_prel_lo21_reloc(0x0, 0x10_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 21,
            align: 0
        }))
    ));
}

#[test]
fn adr_prel_lo21_overflow_negative() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        adr_prel_lo21_reloc(0x10_0001, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 21,
            align: 0
        }))
    ));
}

#[test]
fn adr_prel_lo21_nonzero_offset() {
    // base=0x0FFC, offset=4 → place=0x1000;  diff=0x1008−0x1000=8
    let mut mem = [0u8; 8];
    mem[4..8].copy_from_slice(&ADR.to_le_bytes());
    adr_prel_lo21_reloc(0x0FFC, 0x1008, &mut mem, 4).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 4)), 8);
}

// ═══════════════════════════════════════════════════════════════════════
// adrp_prel_pg_hi21  (base, target, mem, offset)
//
//   imm21 = (Page(target) − Page(place)) / 4096
//   Signed 21-bit page offset → ±4 GiB range
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn adrp_same_page() {
    // Both on page 0x1000 → imm21=0
    let mut mem = insn_buf(ADRP);
    adrp_prel_pg_hi21_reloc(0x1000, 0x1234, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 0);
}

#[test]
fn adrp_next_page() {
    // place page=0x1000; target page=0x2000 → imm21=1
    let mut mem = insn_buf(ADRP);
    adrp_prel_pg_hi21_reloc(0x1ABC, 0x2ABC, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 1);
}

#[test]
fn adrp_prev_page() {
    // place page=0x2000; target page=0x1000 → imm21=−1
    let mut mem = insn_buf(ADRP);
    adrp_prel_pg_hi21_reloc(0x2ABC, 0x1ABC, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), -1);
}

#[test]
fn adrp_max_positive() {
    // imm21 max = (1<<20)−1 page offsets
    // target page = ((1<<20)−1) * 0x1000 = 0xF_FFFF_000
    let mut mem = insn_buf(ADRP);
    adrp_prel_pg_hi21_reloc(0x0, 0xF_FFFF_FFF, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), (1 << 20) - 1);
}

#[test]
fn adrp_max_negative() {
    // imm21 min = −(1<<20);  page diff = −(1<<20)
    // place page = (1<<20)*0x1000 = 0x10_0000_000;  target=0
    let mut mem = insn_buf(ADRP);
    adrp_prel_pg_hi21_reloc(0x10_0000_000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), -(1 << 20));
}

#[test]
fn adrp_overflow_positive() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        adrp_prel_pg_hi21_reloc(0x0, 0x1_0000_0000_0000, &mut mem, 0),
        // TODO Unsupported seems to have obsure semantics.
        Err(Rel64Error::InvalidBits(BitError::Unsupported))
    ));
}

#[test]
fn adrp_overflow_negative() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        adrp_prel_pg_hi21_reloc(0x1_0000_0000_0000, 0x0, &mut mem, 0),
        // TODO Unsupported seems to have obsure semantics.
        // Actually it should be BitError::Overflow.
        Err(Rel64Error::InvalidBits(BitError::Unsupported))
    ),);
}

#[test]
fn adrp_nc_identical_to_checked_in_range() {
    let mut mc = insn_buf(ADRP);
    let mut mn = insn_buf(ADRP);
    adrp_prel_pg_hi21_reloc(0x1000, 0x5678, &mut mc, 0).unwrap();
    adrp_prel_pg_hi21_nc_reloc(0x1000, 0x5678, &mut mn, 0).unwrap();
    assert_eq!(mc, mn);
}

#[test]
fn adrp_nc_no_overflow() {
    // Would be rejected by the checked variant; NC silently truncates
    let mut mem = [0u8; 4];
    adrp_prel_pg_hi21_nc_reloc(0x0, 0x1_0000_0000_0000, &mut mem, 0).unwrap();
}

#[test]
fn adrp_nonzero_offset() {
    // base=0x0FFC, offset=4 → place=0x1000 (page 0x1000)
    // target=0x3ABC → page=0x3000;  imm21=2
    let mut mem = [0u8; 8];
    mem[4..8].copy_from_slice(&ADRP.to_le_bytes());
    adrp_prel_pg_hi21_reloc(0x0FFC, 0x3ABC, &mut mem, 4).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 4)), 2);
}

// Additionaly ADRP tests
#[test]
fn lo12_target_below_lo12_place_typical() {
    // S+A = 0x4_300  →  Page(S+A) = 0x4_000  (lo12 = 0x300)
    // P   = 0x2_A00  →  Page(P)   = 0x2_000  (lo12 = 0xA00)
    //
    // 0x300 < 0xA00, so formulas diverge:
    //   correct: (0x4_000 - 0x2_000) >> 12 = 2
    //   buggy:   Page(0x4_300 - 0x2_A00) = Page(0x1_900) >> 12 = 1
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_reloc(0x2_A00, 0x4_300, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn lo12_target_one_lo12_place_max() {
    // Extreme: target lo12 nearly zero, place lo12 nearly 0xFFF.
    //
    // S+A = 0x3_001  →  Page(S+A) = 0x3_000  (lo12 = 0x001)
    // P   = 0x1_FFF  →  Page(P)   = 0x1_000  (lo12 = 0xFFF)
    //
    //   correct: (0x3_000 - 0x1_000) >> 12 = 2
    //   buggy:   Page(0x3_001 - 0x1_FFF) = Page(0x1_002) >> 12 = 1
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_reloc(0x1_FFF, 0x3_001, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn lo12_target_zero_lo12_place_nonzero() {
    // Target is page-aligned; any non-zero lo12 in place triggers the bug.
    //
    // S+A = 0x5_000  →  Page(S+A) = 0x5_000  (lo12 = 0x000)
    // P   = 0x3_001  →  Page(P)   = 0x3_000  (lo12 = 0x001)
    //
    //   correct: (0x5_000 - 0x3_000) >> 12 = 2
    //   buggy:   Page(0x5_000 - 0x3_001) = Page(0x1_FFF) >> 12 = 1
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_reloc(0x3_001, 0x5_000, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn lo12_target_below_lo12_place_negative_imm() {
    // Backward reference — same divergence condition, negative result.
    //
    // S+A = 0x1_200  →  Page(S+A) = 0x1_000  (lo12 = 0x200)
    // P   = 0x3_800  →  Page(P)   = 0x3_000  (lo12 = 0x800)
    //
    //   correct: (0x1_000 - 0x3_000) >> 12 = -2
    //   buggy:   Page(0x1_200 - 0x3_800) wrapping = Page(…E400) >> 12
    //            interpreted as signed: -3  ← one page off
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_reloc(0x3_800, 0x1_200, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), -2);
}

#[test]
fn lo12_target_below_lo12_place_with_offset() {
    // Confirms offset is included when computing place = base + offset.
    // (With the current impl signature, pass the pre-computed place directly;
    // here offset advances within the buffer, not changing the place value.)
    //
    // place = 0x2_600  (lo12 = 0x600)
    // S+A   = 0x4_300  (lo12 = 0x300)
    //
    // 0x300 < 0x600:
    //   correct: (0x4_000 - 0x2_000) >> 12 = 2
    //   buggy:   Page(0x4_300 - 0x2_600) = Page(0x1_D00) >> 12 = 1
    let mut mem = [0u8; 8];
    mem[4..8].copy_from_slice(&ADRP.to_le_bytes());
    adrp_prel_pg_hi21_reloc(0x2_600, 0x4_300, &mut mem, 4).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 4)), 2);
}

// ─────────────────────────────────────────────────────────────────────
// Same diverging cases for the NC (no-overflow-check) variant
// ─────────────────────────────────────────────────────────────────────

#[test]
fn nc_lo12_target_below_lo12_place_typical() {
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_nc_reloc(0x2_A00, 0x4_300, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn nc_lo12_target_zero_lo12_place_nonzero() {
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_nc_reloc(0x3_001, 0x5_000, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn nc_lo12_target_below_lo12_place_negative_imm() {
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_nc_reloc(0x3_800, 0x1_200, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), -2);
}

// ─────────────────────────────────────────────────────────────────────
// Sanity: cases where the formulas agree (lo12 target >= lo12 place).
// Included to confirm the test logic and to show the reader why the
// failing cases above are the interesting ones.
// ─────────────────────────────────────────────────────────────────────

#[test]
fn sanity_lo12_equal_formulas_agree() {
    // lo12(S+A) = lo12(P) = 0x500  →  no divergence, imm = 2
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_reloc(0x2_500, 0x4_500, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn sanity_lo12_target_above_lo12_place_formulas_agree() {
    // lo12(S+A) = 0xF00 > lo12(P) = 0x100  →  no divergence, imm = 2
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_reloc(0x2_100, 0x4_F00, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn sanity_page_aligned_place_formulas_always_agree() {
    // lo12(P) = 0  →  condition lo12(target) < lo12(place) can never hold
    let mut mem = ADRP.to_le_bytes();
    adrp_prel_pg_hi21_reloc(0x2_000, 0x4_300, &mut mem, 0).unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

// ═══════════════════════════════════════════════════════════════════════
// add_abs_lo12_nc  (target, mem, offset)
//
//   imm12 = target & 0xFFF  (no overflow check)
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn add_abs_lo12_nc_basic() {
    let mut mem = insn_buf(ADD);
    add_abs_lo_12_nc_reloc(0x1ABC, &mut mem, 0).unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0)), 0xABC);
}

#[test]
fn add_abs_lo12_nc_zero() {
    let mut mem = insn_buf(ADD);
    add_abs_lo_12_nc_reloc(0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0)), 0);
}

#[test]
fn add_abs_lo12_nc_max_field() {
    let mut mem = insn_buf(ADD);
    add_abs_lo_12_nc_reloc(0xFFF, &mut mem, 0).unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0)), 0xFFF);
}

#[test]
fn add_abs_lo12_nc_masks_high_bits() {
    let mut mem = insn_buf(ADD);
    add_abs_lo_12_nc_reloc(0xDEAD_BEEF_FFFF_1234, &mut mem, 0).unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0)), 0x234);
}
// ─────────────────────────────────────────────────────────────────────
// Cases where (S+A) & 0xFFF  ≠  (S+A − P) & 0xFFF
// ─────────────────────────────────────────────────────────────────────

#[test]
fn place_nonzero_lo12_typical() {
    // target = 0x2_ABC  →  correct imm12 = 0xABC
    // place  = 0x1_400  →  buggy   imm12 = (0x2_ABC - 0x1_400) & 0xFFF = 0x6BC
    //
    // base=0x1_000, offset=0x400  →  place = 0x1_400
    let mut mem = [0u8; 0x404];
    mem[0x400..0x404].copy_from_slice(&ADD.to_le_bytes());
    Rel64Tag::AddAbsLo12Nc
        .apply(0x1_000, 0x2_ABC, &mut mem, 0x400)
        .unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0x400)), 0xABC);
}

#[test]
fn place_lo12_exceeds_target_lo12() {
    // target = 0x2_200  →  correct imm12 = 0x200
    // place  = 0x1_800  →  buggy   imm12 = (0x2_200 - 0x1_800) & 0xFFF = 0xA00
    //
    // base=0x1_000, offset=0x800  →  place = 0x1_800
    let mut mem = [0u8; 0x804];
    mem[0x800..0x804].copy_from_slice(&ADD.to_le_bytes());
    Rel64Tag::AddAbsLo12Nc
        .apply(0x1_000, 0x2_200, &mut mem, 0x800)
        .unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0x800)), 0x200);
}

#[test]
fn place_lo12_equals_target_lo12() {
    // target = 0x2_500  →  correct imm12 = 0x500
    // place  = 0x1_500  →  buggy   imm12 = (0x2_500 - 0x1_500) & 0xFFF = 0x000
    //
    // base=0x1_000, offset=0x500  →  place = 0x1_500
    let mut mem = [0u8; 0x504];
    mem[0x500..0x504].copy_from_slice(&ADD.to_le_bytes());
    Rel64Tag::AddAbsLo12Nc
        .apply(0x1_000, 0x2_500, &mut mem, 0x500)
        .unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0x500)), 0x500);
}

#[test]
fn target_page_aligned_place_not() {
    // target = 0x3_000  →  correct imm12 = 0x000
    // place  = 0x1_ABC  →  buggy   imm12 = (0x3_000 - 0x1_ABC) & 0xFFF = 0x544
    //
    // base=0x1_000, offset=0xABC  →  place = 0x1_ABC
    let mut mem = [0u8; 0xAC0];
    mem[0xABC..0xAC0].copy_from_slice(&ADD.to_le_bytes());
    Rel64Tag::AddAbsLo12Nc
        .apply(0x1_000, 0x3_000, &mut mem, 0xABC)
        .unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0xABC)), 0x000);
}

#[test]
fn place_from_nonzero_base_and_offset_both_contribute() {
    // Checks that place = base + offset, not just base or just offset.
    //
    // target = 0x5_700  →  correct imm12 = 0x700
    // base=0x1_200, offset=0x400  →  place = 0x1_600
    // buggy: (0x5_700 - 0x1_600) & 0xFFF = 0x100  ← wrong
    let mut mem = [0u8; 0x404];
    mem[0x400..0x404].copy_from_slice(&ADD.to_le_bytes());
    Rel64Tag::AddAbsLo12Nc
        .apply(0x1_200, 0x5_700, &mut mem, 0x400)
        .unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0x400)), 0x700);
}

// ─────────────────────────────────────────────────────────────────────
// Sanity: page-aligned place — both formulas agree, bug is invisible
// ─────────────────────────────────────────────────────────────────────

#[test]
fn sanity_page_aligned_place_formulas_agree() {
    // place = 0x2_000 (page-aligned) → P & 0xFFF = 0
    // Both formulas give the same result; existing tests all look like this.
    let mut mem = ADD.to_le_bytes();
    Rel64Tag::AddAbsLo12Nc
        .apply(0x2_000, 0x4_ABC, &mut mem, 0)
        .unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0)), 0xABC);
}

#[test]
fn sanity_zero_base_zero_offset_formulas_agree() {
    // place = 0 → both formulas identical; this is what the original tests use.
    let mut mem = ADD.to_le_bytes();
    Rel64Tag::AddAbsLo12Nc
        .apply(0, 0x4_ABC, &mut mem, 0)
        .unwrap();
    assert_eq!(dec_imm12(u32_at(&mem, 0)), 0xABC);
}

// ═══════════════════════════════════════════════════════════════════════
// tst_br14  (base, target, mem, offset)
//
//   imm14 = (target − place) / 4
//   Signed 14-bit word offset → byte range [−(1<<15), (1<<15)−4]
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn tst_br14_forward() {
    // place=0x1000;  diff=8;  imm14=2
    let mut mem = insn_buf(TBZ);
    tst_br14_reloc(0x1000, 0x1008, &mut mem, 0).unwrap();
    assert_eq!(dec_imm14(u32_at(&mem, 0)), 2);
}

#[test]
fn tst_br14_backward() {
    // place=0x1008;  diff=−8;  imm14=−2
    let mut mem = insn_buf(TBZ);
    tst_br14_reloc(0x1008, 0x1000, &mut mem, 0).unwrap();
    assert_eq!(dec_imm14(u32_at(&mem, 0)), -2);
}

#[test]
fn tst_br14_max_positive() {
    // imm14 max = (1<<13)−1 = 8191 word offsets → byte diff = 0x7FFC
    let mut mem = insn_buf(TBZ);
    tst_br14_reloc(0x0, 0x7FFC, &mut mem, 0).unwrap();
    assert_eq!(dec_imm14(u32_at(&mem, 0)), (1 << 13) - 1);
}

#[test]
fn tst_br14_max_negative() {
    // imm14 min = −(1<<13) → byte diff = −0x8000;  place=0x8000, target=0
    let mut mem = insn_buf(TBZ);
    tst_br14_reloc(0x8000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm14(u32_at(&mem, 0)), -(1 << 13));
}

#[test]
fn tst_br14_overflow_positive() {
    // byte diff=0x8000 → word imm=1<<13, one above max
    let mut mem = [0u8; 4];
    assert!(matches!(
        tst_br14_reloc(0x0, 0x8000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 14,
            align: 2
        }))
    ));
}

#[test]
fn tst_br14_overflow_negative() {
    // place=0x8004, target=0 → byte diff=−0x8004 → one below min
    let mut mem = [0u8; 4];
    assert!(matches!(
        tst_br14_reloc(0x8004, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 14,
            align: 2
        }))
    ));
}

#[test]
fn tst_br14_unaligned() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        tst_br14_reloc(0x0, 0x2, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Alignment { align: 2 }))
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// cond_br19  (base, target, mem, offset)
//
//   imm19 = (target − place) / 4
//   Signed 19-bit word offset → byte range [−(1<<20), (1<<20)−4]
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn cond_br19_forward() {
    // diff=4;  imm19=1
    let mut mem = insn_buf(BEQ);
    cond_br19_reloc(0x0, 0x0004, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), 1);
}

#[test]
fn cond_br19_backward() {
    // place=0x100;  diff=−0x100;  imm19=−64
    let mut mem = insn_buf(BEQ);
    cond_br19_reloc(0x100, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), -64);
}

#[test]
fn cond_br19_max_positive() {
    // imm19 max = (1<<18)−1 → byte diff = 0x0F_FFFC
    let mut mem = insn_buf(BEQ);
    cond_br19_reloc(0x0, 0x0F_FFFC, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), (1 << 18) - 1);
}

#[test]
fn cond_br19_max_negative() {
    // imm19 min = −(1<<18) → byte diff = −0x10_0000;  place=0x10_0000, target=0
    let mut mem = insn_buf(BEQ);
    cond_br19_reloc(0x10_0000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm19(u32_at(&mem, 0)), -(1 << 18));
}

#[test]
fn cond_br19_overflow_positive() {
    // byte diff=0x10_0000 → word imm=1<<18, one above max
    let mut mem = [0u8; 4];
    assert!(matches!(
        cond_br19_reloc(0x0, 0x10_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 19,
            align: 2
        }))
    ));
}

#[test]
fn cond_br19_overflow_negative() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        cond_br19_reloc(0x10_0004, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 19,
            align: 2
        }))
    ));
}

#[test]
fn cond_br19_unaligned() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        cond_br19_reloc(0x0, 0x2, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Alignment { align: 2 }))
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// jump26  (base, target, mem, offset)
//
//   imm26 = (target − place) / 4
//   Signed 26-bit word offset → byte range [−(1<<27), (1<<27)−4]
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn jump26_forward() {
    // diff=0x10;  imm26=4
    let mut mem = insn_buf(B);
    jump26_reloc(0x0, 0x10, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), 4);
}

#[test]
fn jump26_backward() {
    // place=0x10;  diff=−0x10;  imm26=−4
    let mut mem = insn_buf(B);
    jump26_reloc(0x10, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), -4);
}

#[test]
fn jump26_max_positive() {
    // imm26 max = (1<<25)−1 → byte diff = 0x07FF_FFFC
    let mut mem = insn_buf(B);
    jump26_reloc(0x0, 0x07FF_FFFC, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), (1 << 25) - 1);
}

#[test]
fn jump26_max_negative() {
    // imm26 min = −(1<<25) → byte diff = −0x0800_0000
    // place=0x0800_0000, target=0
    let mut mem = insn_buf(B);
    jump26_reloc(0x0800_0000, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), -(1 << 25));
}

#[test]
fn jump26_overflow_positive() {
    // byte diff=0x0800_0000 → word imm=1<<25, one above max
    let mut mem = [0u8; 4];
    assert!(matches!(
        jump26_reloc(0x0, 0x0800_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 26,
            align: 2
        }))
    ));
}

#[test]
fn jump26_overflow_negative() {
    // place=0x0800_0004, target=0 → one below min
    let mut mem = [0u8; 4];
    assert!(matches!(
        jump26_reloc(0x0800_0004, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 26,
            align: 2
        }))
    ));
}

#[test]
fn jump26_unaligned() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        jump26_reloc(0x0, 0x2, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Alignment { align: 2 }))
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// call26  (base, target, mem, offset)
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn call26_forward() {
    let mut mem = insn_buf(BL);
    call26_reloc(0x0, 0x0004, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), 1);
}

#[test]
fn call26_backward() {
    // place=4;  diff=−4;  imm26=−1
    let mut mem = insn_buf(BL);
    call26_reloc(0x4, 0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), -1);
}

#[test]
fn call26_overflow_positive() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        call26_reloc(0x0, 0x0800_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 26,
            align: 2
        }))
    ));
}

#[test]
fn call26_overflow_negative() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        call26_reloc(0x0800_0004, 0x0, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Overflow {
            significant_bits: 26,
            align: 2
        }))
    ));
}

#[test]
fn call26_unaligned() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        call26_reloc(0x0, 0x2, &mut mem, 0),
        Err(Rel64Error::InvalidBits(BitError::Alignment { align: 2 }))
    ));
}

// ═══════════════════════════════════════════════════════════════════════
// MOV_W relocations  (target, mem, offset)
//
//   Unsigned Gk: S[k*16+15 : k*16] → imm16
//     Overflow if any bit above chunk k is set (except NC variants).
//   Signed Gk:   same chunk, sign-checked to (k+1)*16 bits.
//     Negative → MOVN with ~chunk; non-negative → MOVZ.
// ═══════════════════════════════════════════════════════════════════════

// ── G0 ───────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g0_basic() {
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0_reloc(0xABCD, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xABCD);
}

#[test]
fn mov_w_abs_g0_max() {
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0_reloc(0xFFFF, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xFFFF);
}

#[test]
fn mov_w_abs_g0_overflow() {
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g0_reloc(0x1_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ── G0 NC ─────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g0nc_basic() {
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0nc_reloc(0x1234, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0x1234);
}

#[test]
fn mov_w_abs_g0nc_strips_high_bits() {
    // Only S[15:0] written; upper bits silently discarded
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0nc_reloc(0xDEAD_BEEF_0000_1234, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0x1234);
}

// ── G0 S ──────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g0s_positive() {
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0s_reloc(0x1234, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVZ);
    assert_eq!(dec_movw(i), 0x1234);
}

#[test]
fn mov_w_abs_g0s_max_positive() {
    // 0x7FFF = i16::MAX — largest that fits
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0s_reloc(0x7FFF, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVZ);
    assert_eq!(dec_movw(i), 0x7FFF);
}

#[test]
fn mov_w_abs_g0s_minus_one() {
    // MOVN imm=0 encodes −1
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0s_reloc(-1, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVN);
    assert_eq!(dec_movw(i), 0x0000); // ~(−1)[15:0] = 0
}

#[test]
fn mov_w_abs_g0s_max_negative() {
    // i16::MIN = −0x8000;  imm = ~(−0x8000)[15:0] = 0x7FFF
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0s_reloc(-0x8000, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVN);
    assert_eq!(dec_movw(i), 0x7FFF);
}

#[test]
fn mov_w_abs_g0s_negative_value() {
    // −0x1234;  imm = ~(−0x1234)[15:0] = 0x1233
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g0s_reloc(-0x1234, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVN);
    assert_eq!(dec_movw(i), 0x1233);
}

#[test]
fn mov_w_abs_g0s_overflow_positive() {
    // 0x8000 > i16::MAX
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g0s_reloc(0x8000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

#[test]
fn mov_w_abs_g0s_overflow_negative() {
    // −0x8001 < i16::MIN
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g0s_reloc(-0x8001, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ── G1 ───────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g1_basic() {
    // S[31:16] of 0xABCD_0000 = 0xABCD
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1_reloc(0xABCD_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xABCD);
}

#[test]
fn mov_w_abs_g1_max() {
    // 0xFFFF_FFFF — max value; S[31:16] = 0xFFFF
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1_reloc(0xFFFF_FFFF, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xFFFF);
}

#[test]
fn mov_w_abs_g1_overflow() {
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g1_reloc(0x1_0000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ── G1 NC ─────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g1nc_basic() {
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1nc_reloc(0xABCD_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xABCD);
}

#[test]
fn mov_w_abs_g1nc_strips_high_bits() {
    // Only S[31:16] written; bits [63:32] discarded
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1nc_reloc(0xDEAD_BEEF_ABCD_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xABCD);
}

// ── G1 S ──────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g1s_positive() {
    // 0x7FFF_0000 fits in signed 32-bit; chunk 1 = 0x7FFF
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1s_reloc(0x7FFF_0000, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVZ);
    assert_eq!(dec_movw(i), 0x7FFF);
}

#[test]
fn mov_w_abs_g1s_max_positive() {
    // i32::MAX = 0x7FFF_FFFF;  chunk 1 = 0x7FFF
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1s_reloc(0x7FFF_FFFF, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVZ);
    assert_eq!(dec_movw(i), 0x7FFF);
}

#[test]
fn mov_w_abs_g1s_negative() {
    // −0x8000_0000 = i32::MIN;  ~target = 0x7FFF_FFFF;  chunk 1 = 0x7FFF
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1s_reloc(-0x8000_0000, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVN);
    assert_eq!(dec_movw(i), 0x7FFF);
}

#[test]
fn mov_w_abs_g1s_negative_value() {
    // −0x1234_5678;  ~target = 0x1234_5677;  chunk 1 = 0x1234
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g1s_reloc(-0x1234_5678, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVN);
    assert_eq!(dec_movw(i), 0x1234);
}

#[test]
fn mov_w_abs_g1s_overflow_positive() {
    // 0x8000_0000 = i32::MAX + 1
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g1s_reloc(0x8000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

#[test]
fn mov_w_abs_g1s_overflow_negative() {
    // −0x8000_0001 < i32::MIN
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g1s_reloc(-0x8000_0001, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ── G2 ───────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g2_basic() {
    // S[47:32] of 0x0001_0000_0000 = 0x0001
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g2_reloc(0x0001_0000_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0x0001);
}

#[test]
fn mov_w_abs_g2_max() {
    // 0xFFFF_FFFF_FFFF — max value; S[47:32] = 0xFFFF
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g2_reloc(0xFFFF_FFFF_FFFF, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xFFFF);
}

#[test]
fn mov_w_abs_g2_overflow() {
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g2_reloc(0x0001_0000_0000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ── G2 NC ─────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g2nc_basic() {
    // S[47:32] of 0xDEAD_1234_0000_0000 = 0x1234
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g2nc_reloc(0xDEAD_1234_0000_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0x1234);
}

#[test]
fn mov_w_abs_g2nc_strips_high_bits() {
    // Bits [63:48] discarded without error
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g2nc_reloc(0xFFFF_ABCD_0000_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xABCD);
}

// ── G2 S ──────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g2s_positive() {
    // 0x0000_1234_0000_0000 fits in signed 48-bit; chunk 2 = 0x1234
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g2s_reloc(0x0000_1234_0000_0000_i64, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVZ);
    assert_eq!(dec_movw(i), 0x1234);
}

#[test]
fn mov_w_abs_g2s_negative() {
    // −0x1234_0000_0000;  ~target = 0x1233_FFFF_FFFF;  chunk 2 = 0x1233
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g2s_reloc(-0x1234_0000_0000_i64, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(mov_w_opc(i), MOV_W_OPC_MOVN);
    assert_eq!(dec_movw(i), 0x1233);
}

#[test]
fn mov_w_abs_g2s_overflow_positive() {
    // 2^47 — one above signed 48-bit max (2^47 − 1)
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g2s_reloc(0x0000_8000_0000_0000_u64 as i64, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

#[test]
fn mov_w_abs_g2s_overflow_negative() {
    // −(2^47 + 1) — one below signed 48-bit min (−2^47)
    let mut mem = insn_buf(MOVZ);
    assert!(matches!(
        mov_w_abs_g2s_reloc(-0x8000_0000_0001_i64, &mut mem, 0),
        Err(Rel64Error::InvalidValue(_))
    ));
}

// ── G3 ───────────────────────────────────────────────────────────────

#[test]
fn mov_w_abs_g3_basic() {
    // S[63:48] of 0xBEEF_0000_0000_0000 = 0xBEEF
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g3_reloc(0xBEEF_0000_0000_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xBEEF);
}

#[test]
fn mov_w_abs_g3_max() {
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g3_reloc(0xFFFF_0000_0000_0000, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xFFFF);
}

#[test]
fn mov_w_abs_g3_zero() {
    let mut mem = insn_buf(MOVZ);
    mov_w_abs_g3_reloc(0x0, &mut mem, 0).unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0x0000);
}

// ── Cross-cutting: bits outside the immediate field are preserved ─────

#[test]
fn patch_preserves_non_immediate_fields() {
    // MOVK X5, #0 (opc=11, Rd=5) → 0xF280_0005
    let movk_x5: u32 = 0xF280_0005;
    let mut mem = movk_x5.to_le_bytes().to_vec();
    mov_w_abs_g0nc_reloc(0xABCD, &mut mem, 0).unwrap();
    let i = u32_at(&mem, 0);
    assert_eq!(dec_movw(i), 0xABCD);
    assert_eq!(mov_w_opc(i), 0b11); // opc preserved
    assert_eq!(i & 0x1F, 5); // Rd preserved
}

// ═══════════════════════════════════════════════════════════════════════
// Rel64Tag::apply  — checks dispatch and the place = base + offset formula
// ═══════════════════════════════════════════════════════════════════════

#[test]
fn tag_none_is_noop() {
    let mut mem = [0xFFu8; 8];
    Rel64Tag::None.apply(0, 0, &mut mem, 0).unwrap();
    assert!(mem.iter().all(|&b| b == 0xFF));
}

#[test]
fn tag_abs64_roundtrip() {
    let mut mem = [0u8; 8];
    Rel64Tag::Abs64
        .apply(0, 0x1122_3344_5566_7788, &mut mem, 0)
        .unwrap();
    assert_eq!(u64_at(&mem, 0), 0x1122_3344_5566_7788);
}

#[test]
fn tag_abs32_via_apply() {
    let mut mem = [0u8; 4];
    Rel64Tag::Abs32.apply(0, 0x7EAD_BEEF, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0), 0x7EAD_BEEF);
}

#[test]
fn tag_prel32_via_apply() {
    // base=0, offset=0 → place=0;  diff=i32::MAX
    let mut mem = [0u8; 4];
    Rel64Tag::PRel32
        .apply(0x0, 0x7FFF_FFFF, &mut mem, 0)
        .unwrap();
    assert_eq!(u32_at(&mem, 0) as i32, i32::MAX);
}

#[test]
fn tag_jump26_via_apply() {
    // base=0, offset=0 → place=0;  diff=8;  imm26=2
    let mut mem = insn_buf(B);
    Rel64Tag::Jump26.apply(0x0, 0x0008, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), 2);
}

#[test]
fn tag_call26_via_apply() {
    // base=0, offset=0 → place=0;  diff=4;  imm26=1
    let mut mem = insn_buf(BL);
    Rel64Tag::Call26.apply(0x0, 0x0004, &mut mem, 0).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 0)), 1);
}

#[test]
fn tag_adrp_via_apply() {
    // base=0x1100, offset=0 → place=0x1100 (page 0x1000)
    // target=0x3500 → page 0x3000;  imm21=2
    let mut mem = [0u8; 4];
    Rel64Tag::AdrPrelPgHi21
        .apply(0x1100, 0x3500, &mut mem, 0)
        .unwrap();
    assert_eq!(dec_imm21_adr(u32_at(&mem, 0)), 2);
}

#[test]
fn tag_mov_w_g1nc_via_apply() {
    let mut mem = insn_buf(MOVZ);
    Rel64Tag::MovWAbsG1Nc
        .apply(0, 0xDEAD_BEEF_ABCD_0000, &mut mem, 0)
        .unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xABCD);
}

#[test]
fn tag_mov_w_g2nc_via_apply() {
    let mut mem = insn_buf(MOVZ);
    Rel64Tag::MovWAbsG2Nc
        .apply(0, 0xDEAD_1234_0000_0000, &mut mem, 0)
        .unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0x1234);
}

#[test]
fn tag_mov_w_g3_via_apply() {
    let mut mem = insn_buf(MOVZ);
    Rel64Tag::MovWAbsG3
        .apply(0, 0xBEEF_0000_0000_0000, &mut mem, 0)
        .unwrap();
    assert_eq!(dec_movw(u32_at(&mem, 0)), 0xBEEF);
}

#[test]
fn tag_place_is_base_plus_offset() {
    // Verifies apply() uses place = base + offset, not just base.
    // B at mem[4];  base=0x0FFC, offset=4 → place=0x1000
    // target=0x1010;  diff=0x10;  imm26=4
    let mut mem = [0u8; 8];
    mem[4..8].copy_from_slice(&B.to_le_bytes());
    Rel64Tag::Jump26.apply(0x0FFC, 0x1010, &mut mem, 4).unwrap();
    assert_eq!(dec_imm26(u32_at(&mem, 4)), 4);
}
