/* Tests based on code generated by Claude Sonnet 4.6. */
use super::*;

// opc values for MOVW instructions.
const MOVW_OPC_MOVZ: u32 = 0b10;
const MOVW_OPC_MOVN: u32 = 0b00;

fn movw_opc(insn: u32) -> u32 {
    (insn >> 29) & 0x3
}
// ── Byte-level accessors ──────────────────────────────────────────────────

fn u16_at(mem: &[u8], off: usize) -> u16 {
    u16::from_le_bytes(mem[off..off + 2].try_into().unwrap())
}

fn u32_at(mem: &[u8], off: usize) -> u32 {
    u32::from_le_bytes(mem[off..off + 4].try_into().unwrap())
}

fn u64_at(mem: &[u8], off: usize) -> u64 {
    u64::from_le_bytes(mem[off..off + 8].try_into().unwrap())
}

// ── Instruction-field decoders ────────────────────────────────────────────

/// Sign-extend a `width`-bit unsigned value to i32.
fn sign_ext(raw: u32, width: u32) -> i32 {
    let shift = 32 - width;
    ((raw << shift) as i32) >> shift
}

fn insn_imm14(insn: u32) -> i32 {
    sign_ext((insn >> 5) & 0x3FFF, 14)
}
fn insn_imm19(insn: u32) -> i32 {
    sign_ext((insn >> 5) & 0x0007_FFFF, 19)
}
fn insn_imm26(insn: u32) -> i32 {
    sign_ext(insn & 0x03FF_FFFF, 26)
}

fn insn_imm21_adr(insn: u32) -> i32 {
    let immlo = (insn >> 29) & 0x3;
    let immhi = (insn >> 5) & 0x0007_FFFF;
    sign_ext((immhi << 2) | immlo, 21)
}

fn insn_imm12_add(insn: u32) -> u32 {
    (insn >> 10) & 0xFFF
}
fn insn_mov_w_imm(insn: u32) -> u16 {
    ((insn >> 5) & 0xFFFF) as u16
}

// ── get_bytes_mut error-variant tests ─────────────────────────────────────

#[test]
fn get_bytes_mut_ok() {
    let mut mem = [1u8, 2, 3, 4, 5, 6, 7, 8];
    let arr: &mut [u8; 4] = get_bytes_mut(&mut mem, 2).unwrap();
    assert_eq!(*arr, [3, 4, 5, 6]);
}

#[test]
fn get_bytes_mut_invalid_offset() {
    let mut mem = [0u8; 4];
    assert_eq!(
        get_bytes_mut::<4>(&mut mem, 5),
        Err(Rel64Error::InvalidOffset { offset: 5 })
    );
}

#[test]
fn get_bytes_mut_not_enough_memory() {
    let mut mem = [0u8; 4];
    // offset 2 is valid but only 2 bytes remain — not enough for 4.
    assert_eq!(
        get_bytes_mut::<4>(&mut mem, 2),
        Err(Rel64Error::NotEnoughMemory { offset: 2 })
    );
}

// ── Static data relocations ───────────────────────────────────────────────

#[test]
fn abs64_basic() {
    let mut mem = [0u8; 16];
    abs64_reloc(0xDEAD_BEEF_CAFE_1234, &mut mem, 4).unwrap();
    assert_eq!(u64_at(&mem, 4), 0xDEAD_BEEF_CAFE_1234);
}

#[test]
fn abs32_ok() {
    let mut mem = [0u8; 8];
    abs32_reloc(0x0000_ABCD, &mut mem, 2).unwrap();
    assert_eq!(u32_at(&mem, 2), 0x0000_ABCD);
}

#[test]
fn abs32_overflow() {
    let mut mem = [0u8; 8];
    assert!(matches!(
        abs32_reloc(0x1_0000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue { .. })
    ));
}

#[test]
fn abs16_ok() {
    let mut mem = [0u8; 4];
    abs16_reloc(0xBEEF, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0), 0xBEEF);
}

#[test]
fn abs16_overflow() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        abs16_reloc(0x1_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue { .. })
    ));
}

#[test]
fn prel64_forward_and_backward() {
    let mut mem = [0u8; 16];
    prel64_reloc(0x1000, 0x2000, &mut mem, 0).unwrap();
    assert_eq!(u64_at(&mem, 0), 0x1000u64);
    prel64_reloc(0x2000, 0x1000, &mut mem, 0).unwrap();
    assert_eq!(u64_at(&mem, 0) as i64, -0x1000i64);
}

#[test]
fn prel32_in_range() {
    let mut mem = [0u8; 8];
    prel32_reloc(0x4000, 0x5000, &mut mem, 0).unwrap();
    assert_eq!(u32_at(&mem, 0) as i32, 0x1000);
}

#[test]
fn prel32_overflow() {
    let mut mem = [0u8; 8];
    assert!(matches!(
        prel32_reloc(0x0, 0xC000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue { .. })
    ));
}

#[test]
fn prel16_in_range() {
    let mut mem = [0u8; 4];
    prel16_reloc(0x3FFF, 0x4000, &mut mem, 0).unwrap();
    assert_eq!(u16_at(&mem, 0) as i16, 1);
}

#[test]
fn prel16_overflow() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        prel16_reloc(0x0, 0x1_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue { .. })
    ));
}

// ── Buffer-size error variants ────────────────────────────────────────────

#[test]
fn invalid_offset_error() {
    let mut mem = [0u8; 4];
    assert_eq!(
        abs64_reloc(0, &mut mem, 8),
        Err(Rel64Error::InvalidOffset { offset: 8 })
    );
}

#[test]
fn not_enough_memory_error() {
    let mut mem = [0u8; 4];
    assert_eq!(
        abs64_reloc(0, &mut mem, 0),
        Err(Rel64Error::NotEnoughMemory { offset: 0 })
    );
}

// ── LDR literal (LdPrelLo19) ──────────────────────────────────────────────

#[test]
fn ld_prel_lo19_forward() {
    let mut mem = 0x5800_0000u32.to_le_bytes().to_vec();
    ld_prel_lo19_reloc(0x0000, 0x0008, &mut mem, 0).unwrap();
    assert_eq!(insn_imm19(u32_at(&mem, 0)), 2);
}

#[test]
fn ld_prel_lo19_negative() {
    let mut mem = 0x5800_0000u32.to_le_bytes().to_vec();
    ld_prel_lo19_reloc(0x0100, 0x0000, &mut mem, 0).unwrap();
    assert_eq!(insn_imm19(u32_at(&mem, 0)), -64);
}

#[test]
fn ld_prel_lo19_unaligned() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        ld_prel_lo19_reloc(0x0000, 0x0001, &mut mem, 0),
        Err(Rel64Error::InvalidBits(..))
    ));
}

#[test]
fn ld_prel_lo19_overflow() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        ld_prel_lo19_reloc(0x0, 0x20_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(..))
    ));
}

// ── ADR (AdrPrelLo21) ─────────────────────────────────────────────────────

#[test]
fn adr_prel_lo21_basic() {
    let mut mem = 0x0000_0001u32.to_le_bytes().to_vec();
    adr_prel_lo21_reloc(0x1000, 0x1004, &mut mem, 0).unwrap();
    assert_eq!(insn_imm21_adr(u32_at(&mem, 0)), 4);
}

#[test]
fn adr_prel_lo21_negative() {
    let mut mem = 0x0000_0001u32.to_le_bytes().to_vec();
    adr_prel_lo21_reloc(0x1000, 0x0FF8, &mut mem, 0).unwrap();
    assert_eq!(insn_imm21_adr(u32_at(&mem, 0)), -8);
}

#[test]
fn adr_prel_lo21_overflow() {
    let mut mem = [0u8; 4];
    let res = adr_prel_lo21_reloc(0x0, 0x20_0000, &mut mem, 0);
    assert!(matches!(res, Err(Rel64Error::InvalidBits(..))), "{res:?}");
}

// ── ADRP (AdrPrelPgHi21) ──────────────────────────────────────────────────

#[test]
fn adrp_same_page() {
    let mut mem = [0u8; 4];
    adrp_prel_pg_hi21_reloc(0x1000, 0x1234, &mut mem, 0).unwrap();
    assert_eq!(insn_imm21_adr(u32_at(&mem, 0)), 0);
}

#[test]
fn adrp_next_page() {
    let mut mem = [0u8; 4];
    adrp_prel_pg_hi21_reloc(0x1ABC, 0x2ABC, &mut mem, 0).unwrap();
    assert_eq!(insn_imm21_adr(u32_at(&mem, 0)), 1);
}

#[test]
fn adrp_overflow() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        adrp_prel_pg_hi21_reloc(0x0, 0x1_0000_0000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(..))
    ));
}

#[test]
fn adrp_nc_no_overflow() {
    let mut mem = [0u8; 4];
    // Would overflow the checked variant; NC must succeed silently.
    adrp_prel_pg_hi21_nc_reloc(0x0, 0x1_0000_0000_0000, &mut mem, 0).unwrap();
}

// ── ADD lo12 (AddAbsLo12Nc) ───────────────────────────────────────────────

#[test]
fn add_abs_lo12_nc_basic() {
    let mut mem = 0x9100_0020u32.to_le_bytes().to_vec();
    add_abs_lo_12_nc_reloc(0, 0x1ABC, &mut mem, 0).unwrap();
    assert_eq!(insn_imm12_add(u32_at(&mem, 0)), 0xABC);
}

#[test]
fn add_abs_lo12_nc_masks_high_bits() {
    let mut mem = 0x9100_0020u32.to_le_bytes().to_vec();
    add_abs_lo_12_nc_reloc(0, 0xFFFF_1234, &mut mem, 0).unwrap();
    assert_eq!(insn_imm12_add(u32_at(&mem, 0)), 0x234);
}

// ── Control-flow relocations ──────────────────────────────────────────────

#[test]
fn tst_br14_basic() {
    let mut mem = 0x3600_0000u32.to_le_bytes().to_vec();
    tst_br14_reloc(0x1000, 0x1008, &mut mem, 0).unwrap();
    assert_eq!(insn_imm14(u32_at(&mem, 0)), 2);
}

#[test]
fn tst_br14_overflow() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        tst_br14_reloc(0x0, 0x1_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(..))
    ));
}

#[test]
fn tst_br14_unaligned() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        tst_br14_reloc(0x0, 0x1, &mut mem, 0),
        Err(Rel64Error::InvalidBits(..))
    ));
}

#[test]
fn cond_br19_basic() {
    let mut mem = 0x5400_0000u32.to_le_bytes().to_vec();
    cond_br19_reloc(0x0000, 0x0004, &mut mem, 0).unwrap();
    assert_eq!(insn_imm19(u32_at(&mem, 0)), 1);
}

#[test]
fn cond_br19_negative() {
    let mut mem = 0x5400_0000u32.to_le_bytes().to_vec();
    cond_br19_reloc(0x0100, 0x0000, &mut mem, 0).unwrap();
    assert_eq!(insn_imm19(u32_at(&mem, 0)), -64);
}

#[test]
fn jump26_basic() {
    let mut mem = 0x1400_0000u32.to_le_bytes().to_vec();
    jump26_reloc(0x0000, 0x0010, &mut mem, 0).unwrap();
    assert_eq!(insn_imm26(u32_at(&mem, 0)), 4);
}

#[test]
fn jump26_overflow() {
    let mut mem = [0u8; 4];
    assert!(matches!(
        jump26_reloc(0x0, 0x1000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(..))
    ));
}

#[test]
fn call26_basic() {
    let mut mem = 0x9400_0000u32.to_le_bytes().to_vec();
    call26_reloc(0x0000, 0x0004, &mut mem, 0).unwrap();
    assert_eq!(insn_imm26(u32_at(&mem, 0)), 1);
}

#[test]
fn call26_names_itself_in_error() {
    // jump26 and call26 share implementation but must report distinct names.
    let mut mem = [0u8; 4];
    assert!(matches!(
        call26_reloc(0x0, 0x1000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidBits(..))
    ));
}

// ── MOVW relocations ──────────────────────────────────────────────────────

// MOVZ X0, #0: sf=1 opc=10 hw=00 → 0xD2800000
const MOVZ_X0: u32 = 0xD280_0000;

#[test]
fn mov_w_abs_g0_basic() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g0_reloc(0xABCD, &mut mem, 0).unwrap();
    assert_eq!(insn_mov_w_imm(u32_at(&mem, 0)), 0xABCD);
}

#[test]
fn mov_w_abs_g0_overflow() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    assert!(matches!(
        mov_w_abs_g0_reloc(0x1_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(..))
    ));
}

#[test]
fn mov_w_abs_g0nc_no_overflow() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g0nc_reloc(0xDEAD_BEEF_0000_1234u64, &mut mem, 0).unwrap();
    assert_eq!(insn_mov_w_imm(u32_at(&mem, 0)), 0x1234);
}

#[test]
fn mov_w_abs_g1_basic() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g1_reloc(0x0001_0000, &mut mem, 0).unwrap();
    assert_eq!(insn_mov_w_imm(u32_at(&mem, 0)), 0x0001);
}

#[test]
fn mov_w_abs_g1_overflow() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    assert!(matches!(
        mov_w_abs_g1_reloc(0x1_0000_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue(..))
    ));
}

#[test]
fn mov_w_abs_g2_basic() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g2_reloc(0x0001_0000_0000, &mut mem, 0).unwrap();
    assert_eq!(insn_mov_w_imm(u32_at(&mem, 0)), 0x0001);
}

#[test]
fn mov_w_abs_g3_basic() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g3_reloc(0xBEEF_0000_0000_0000u64, &mut mem, 0).unwrap();
    assert_eq!(insn_mov_w_imm(u32_at(&mem, 0)), 0xBEEF);
}

#[test]
fn mov_w_abs_g0s_positive() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g0s_reloc(0x1234, &mut mem, 0).unwrap();
    let insn = u32_at(&mem, 0);
    assert_eq!(movw_opc(insn), MOVW_OPC_MOVZ);
    assert_eq!(insn_mov_w_imm(insn), 0x1234);
}

#[test]
fn mov_w_abs_g0s_minus_one() {
    // -1: MOVN X0, #0 encodes ~0 = -1
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g0s_reloc(-1i64, &mut mem, 0).unwrap();
    let insn = u32_at(&mem, 0);
    assert_eq!(movw_opc(insn), MOVW_OPC_MOVN);
    assert_eq!(insn_mov_w_imm(insn), 0x0000);
}

#[test]
fn mov_w_abs_g0s_negative_value() {
    // -0x1234: MOVN with imm = ~(-0x1234)[15:0] = 0x1233
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g0s_reloc(-0x1234, &mut mem, 0).unwrap();
    let insn = u32_at(&mem, 0);
    assert_eq!(movw_opc(insn), MOVW_OPC_MOVN);
    assert_eq!(insn_mov_w_imm(insn), 0x1233);
}

#[test]
fn mov_w_abs_g1s_negative() {
    // -0x8000_0000: chunk 1 of ~(-0x8000_0000) >> 16 = 0x7FFF
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    mov_w_abs_g1s_reloc(-0x8000_0000, &mut mem, 0).unwrap();
    let insn = u32_at(&mem, 0);
    assert_eq!(movw_opc(insn), MOVW_OPC_MOVN);
    assert_eq!(insn_mov_w_imm(insn), 0x7FFF);
}

#[test]
fn mov_w_abs_g0s_overflow() {
    let mut mem = MOVZ_X0.to_le_bytes().to_vec();
    assert!(matches!(
        mov_w_abs_g0s_reloc(0x1_0000, &mut mem, 0),
        Err(Rel64Error::InvalidValue { .. })
    ));
}

// ── Tag dispatch ──────────────────────────────────────────────────────────

#[test]
fn tag_none_is_noop() {
    let mut mem = [0xFFu8; 8];
    Rel64Tag::None.apply(0, 0, &mut mem, 0).unwrap();
    assert!(mem.iter().all(|&b| b == 0xFF));
}

#[test]
fn tag_abs64_roundtrip() {
    let mut mem = [0u8; 8];
    Rel64Tag::Abs64
        .apply(0, 0x1122_3344_5566_7788, &mut mem, 0)
        .unwrap();
    assert_eq!(u64_at(&mem, 0), 0x1122_3344_5566_7788);
}

#[test]
fn tag_jump26_via_apply() {
    let mut mem = 0x1400_0000u32.to_le_bytes().to_vec();
    // base=0, offset=0 → place=0; target=8 → imm26=2
    Rel64Tag::Jump26.apply(0x0, 0x0008, &mut mem, 0).unwrap();
    assert_eq!(insn_imm26(u32_at(&mem, 0)), 2);
}

#[test]
fn tag_adrp_via_apply() {
    let mut mem = [0u8; 4];
    // base=0x1100, offset=0 → place=0x1100 (page 0x1000)
    // target=0x3500 (page 0x3000) → page diff = 2
    Rel64Tag::AdrPrelPgHi21
        .apply(0x1100, 0x3500, &mut mem, 0)
        .unwrap();
    assert_eq!(insn_imm21_adr(u32_at(&mem, 0)), 2);
}
