[package]
name = "harm-test-utils"
version = "0.1.0"
edition = "2024"
license = "BSD-3-Clause"
authors = ["Ivan Boldyrev <lispnik@gmail.com>"]

[dependencies]
aarchmrs-types = { workspace = true }
hex = "0.4.3"
thiserror = "2.0.12"
