[package]
name = "aarchmrs-parser"
version = "0.1.0"
edition = "2024"
description = "AARCHMRS simple parser"
license = "MIT"
authors = ["Ivan Boldyrev <lispnik@gmail.com>"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
